nombre = input('Introduce tu nombre:')
apellido = input('Introduce tu apellido:')
edad = int (input('Introduce tu edad:'))
correo = input('Introduce tu correo electronico:')
telefono = input('Introduce tu telefono:')

print('Nombre: ' + nombre)
print('Apellido: ' + apellido)
print('Tengo: ' + str(edad) + ' Años')
print('Correro: ' + correo)
print('Telefono: ' + telefono)
